"""empty message

Revision ID: 16617d0a3b5d
Revises: e1c474164200
Create Date: 2023-09-26 14:18:00.740706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16617d0a3b5d'
down_revision = 'e1c474164200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_data', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('avatar_data')

    # ### end Alembic commands ###
